[component]
name = "Fan Attachment"
id = "@interrobang/fans/fan_attachment"
version = "0.1.1"
icon = "./icon.png"

[[property]]
id = "color"
name = "Color"
input_type = "color"
default_value = 0x000000

