[component]
name = "Fan"
version = "0.1.1"

[[property]]
id = "multiplier"
name = "Multiplier"
input_type = "slider"
default_value = 1
min_value = 0.1
max_value = 10

[[property]]
id = "size_multiplier"
name = "Size Multiplier"
input_type = "slider"
default_value = 1
min_value = 0.1
max_value = 10

[[property]]
id = "disable_particles"
name = "Disable Particles"
input_type = "toggle"
default_value = false

